In [1]:
import numpy as np

In [2]:
arr = np.array([10 , 100 , 20 , 30 , 40 , 90])
arr

array([ 10, 100,  20,  30,  40,  90])

In [3]:
arr.size

6

In [7]:
arr[[1,4]]

array([100,  40])

In [9]:
arr

array([ 10, 100,  20,  30,  40,  90])

In [8]:
arr[2:100]

array([20, 30, 40, 90])

In [10]:
ls = [1,2,2,10]
ls

[1, 2, 2, 10]

In [11]:
ls[0:100]

[1, 2, 2, 10]

In [12]:
ls[100]

IndexError: list index out of range

In [13]:
arr

array([ 10, 100,  20,  30,  40,  90])

In [14]:
arr.mean()

np.float64(48.333333333333336)

In [15]:
np.mean(arr)

np.float64(48.333333333333336)

In [16]:
np.median(arr)

np.float64(35.0)

In [17]:
arr

array([ 10, 100,  20,  30,  40,  90])

In [23]:
arr.argmax()  # return index of maximum of given array

np.int64(1)

In [19]:
arr.argmin()  # return idex of minimum of given array

np.int64(0)

In [21]:
arr.argmax?

Docstring:
a.argmax(axis=None, out=None, *, keepdims=False)

Return indices of the maximum values along the given axis.

Refer to `numpy.argmax` for full documentation.

See Also
--------
numpy.argmax : equivalent function
Type:      builtin_function_or_method

In [22]:
arr

array([ 10, 100,  20,  30,  40,  90])

In [24]:
arr.sum()   # sum of given array

np.int64(290)

In [25]:
arr.std()  # standard deviation of array

np.float64(34.35921354681384)

In [27]:
arr.var()   # variance of array

np.float64(1180.5555555555557)

### Metrix

In [35]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.array([
    [10 , 20 , 40] , 
    [80 , 90 , 100] ,
    [120 , 130 , 440]
])
         

array([[ 10,  20,  40],
       [ 80,  90, 100],
       [120, 130, 440]])

In [32]:
arr.shape  #---> (row , columns)

(3, 3)

In [33]:
arr = np.array([
    [10 , 20] , 
    [80 , 90] ,
    [120 , 130]
])

In [34]:
arr.shape

(3, 2)

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.size  #---> Total number of values

9

In [39]:
len(arr)  #-->how many vectors are there in a list

3

In [41]:
arr.ndim   #--> dimention of the array (This is 2D array)

2

### SLICING

In [43]:
arr[0:2]   #--> 0 se 2 tk ki rows dedo

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [47]:
arr[:: , 0:2]  # column aagye 0 and 1 wale

array([[1, 2],
       [4, 5],
       [7, 8]])

In [48]:
arr[1::]

array([[4, 5, 6],
       [7, 8, 9]])

In [49]:
arr[1:: , :2:]

array([[4, 5],
       [7, 8]])

In [50]:
arr[1:: , 1::]

array([[5, 6],
       [8, 9]])

In [51]:
arr[1:: , 1:2]

array([[5],
       [8]])

In [55]:
arr[0:2:2]

array([[1, 2, 3]])

In [58]:
garvita = np.array([
    [10 , 20 , 40] , 
    [80 , 90 , 100] ,
    [120 , 130 , 440],
    [30 , 56 , 78],
    [9 , 34 , 23],
    [45 , 23 , 90]
])
garvita

array([[ 10,  20,  40],
       [ 80,  90, 100],
       [120, 130, 440],
       [ 30,  56,  78],
       [  9,  34,  23],
       [ 45,  23,  90]])

In [61]:
garvita[0:5:2]

array([[ 10,  20,  40],
       [120, 130, 440],
       [  9,  34,  23]])

In [62]:
garvita[::,0:3:2]

array([[ 10,  40],
       [ 80, 100],
       [120, 440],
       [ 30,  78],
       [  9,  23],
       [ 45,  90]])

In [63]:
garvita[::-1]

array([[ 45,  23,  90],
       [  9,  34,  23],
       [ 30,  56,  78],
       [120, 130, 440],
       [ 80,  90, 100],
       [ 10,  20,  40]])

In [65]:
garvita[2:4: , 1:2:]

array([[130],
       [ 56]])

In [66]:
arr # 4 6
      7 9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr[1: , ::2]

array([[4, 6],
       [7, 9]])

In [71]:
arr[[0 , 2] , [0 , 1]]

array([1, 8])

In [72]:
arr[::-1 , ::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [73]:
arr[0:2 , 1:3:]

array([[2, 3],
       [5, 6]])

In [78]:
arr[[0,2] , [0,1]]   #--> 0 row ka 0 column and 2 row ka 1 column 

array([1, 8])

In [79]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
arr[[0,2],]  # Indexing

array([[1, 2, 3],
       [7, 8, 9]])

In [84]:
arr[[0,2,0],[0,1,2]]   #--> phele first row jo chaiye then second row then third fir afte comma write first column then second column then third column

array([1, 8, 3])

In [86]:
(1+5+9) - (3+5+7)

0

In [87]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
sum(arr[[0,1,2],[0,1,2]])-sum(arr[[0,1,2],[2,1,0]])

np.int64(0)

In [99]:
sum(np.diagonal(arr))- sum(np.diagonal(arr[::,::-1]))

np.int64(0)

In [102]:
ls=[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [103]:
v=np.random.randint(1,20,18)
v

array([ 8, 18,  7, 19, 19, 11, 15,  4, 11, 14, 16,  2,  2, 11, 18,  8, 18,
        3], dtype=int32)

In [104]:
v.shape

(18,)

In [108]:
x = v.reshape(6,3)  # multiply should be 18 because 18 elements are there in metrix
x

array([[ 8, 18,  7],
       [19, 19, 11],
       [15,  4, 11],
       [14, 16,  2],
       [ 2, 11, 18],
       [ 8, 18,  3]], dtype=int32)

In [106]:
v.reshape([3,6])

array([[ 8, 18,  7, 19, 19, 11],
       [15,  4, 11, 14, 16,  2],
       [ 2, 11, 18,  8, 18,  3]], dtype=int32)

In [109]:
v.reshape(9,2)

array([[ 8, 18],
       [ 7, 19],
       [19, 11],
       [15,  4],
       [11, 14],
       [16,  2],
       [ 2, 11],
       [18,  8],
       [18,  3]], dtype=int32)