In [1]:
import numpy as np

In [2]:
arr = np.array([
    [1, 2, 4],
    [4, 8 , 10],
    [11, 14, 19]
])

In [3]:
arr

array([[ 1,  2,  4],
       [ 4,  8, 10],
       [11, 14, 19]])

In [4]:
arr.size

9

In [5]:
arr.ndim

2

In [6]:
arr + 2

array([[ 3,  4,  6],
       [ 6, 10, 12],
       [13, 16, 21]])

In [7]:
arr

array([[ 1,  2,  4],
       [ 4,  8, 10],
       [11, 14, 19]])

In [8]:
len(arr)

3

arr[row_slicing , column_slicing]

In [9]:
arr

array([[ 1,  2,  4],
       [ 4,  8, 10],
       [11, 14, 19]])

In [10]:
arr[1:: , 1::]

array([[ 8, 10],
       [14, 19]])

In [13]:
arr[[0,1,2],[0,1,2]]   #indexing

array([ 1,  8, 19])

In [14]:
arr[[0,2],[1,1]]

array([ 2, 14])

In [15]:
arr

array([[ 1,  2,  4],
       [ 4,  8, 10],
       [11, 14, 19]])

In [16]:
arr.mean()

np.float64(8.11111111111111)

In [17]:
arr.mean()   # shift + tab gives documentation of 

np.float64(8.11111111111111)

In [18]:
arr.mean(axis = 0)

array([ 5.33333333,  8.        , 11.        ])

In [20]:
(1+4+11) / 3

5.333333333333333

In [21]:
arr

array([[ 1,  2,  4],
       [ 4,  8, 10],
       [11, 14, 19]])

In [24]:
arr[0::2,0::2]

array([[ 1,  4],
       [11, 19]])

In [25]:
arr.mean(axis=1)

array([ 2.33333333,  7.33333333, 14.66666667])

In [27]:
arr.sum()

np.int64(73)

In [28]:
arr.sum(axis=0)

array([16, 24, 33])

In [29]:
arr

array([[ 1,  2,  4],
       [ 4,  8, 10],
       [11, 14, 19]])

In [32]:
arr1= np.array([10,100,20,40])

In [33]:
arr1

array([ 10, 100,  20,  40])

In [43]:
x = arr1   # changes in one are reflected in other. This is not copy. Id of both x and arr1 are same

In [37]:
arr1

array([ 10, 100,  20,  40])

In [38]:
x

array([ 10, 100,  20,  40])

In [39]:
x[0] = 101
x

array([101, 100,  20,  40])

In [40]:
arr1

array([101, 100,  20,  40])

In [41]:
id(x)

2165469743120

In [42]:
id(arr1)

2165469743120

In [49]:
x = arr1.copy()   # This is the copy. x is the copy of arr1. chnages in x does not reflect in arr1. Id of both are different
x 

array([101, 100,  20,  40])

In [45]:
x[0] = 2000
x

array([2000,  100,   20,   40])

In [46]:
arr1

array([101, 100,  20,  40])

In [47]:
id(arr1)

2165469743120

In [48]:
id(x)

2165469742736

In [51]:
arr

array([[ 1,  2,  4],
       [ 4,  8, 10],
       [11, 14, 19]])

In [52]:
arr.mean()

np.float64(8.11111111111111)

In [55]:
(1 + 2 + 4)/3

2.3333333333333335

In [56]:
arr.mean(axis = 1)

array([ 2.33333333,  7.33333333, 14.66666667])

In [57]:
(4+8+10)/3

7.333333333333333

In [58]:
arr.mean(axis = 0)

array([ 5.33333333,  8.        , 11.        ])

In [64]:
%%writefile data.csv
quantity , price , sale   # 1st header
1 , 100 , 200   #2nd header
4 , 120 , 3000   #3 header
5 , 100 , 3500
6 , 140 , 8000

Overwriting data.csv


In [68]:
d = np.genfromtxt("data.csv" , skip_header = 1 , delimiter = "," , dtype = 'int')   # skip_header tells how many header to be skipped here we have skipped 2 headers 
d

array([[   1,  100,  200],
       [   4,  120, 3000],
       [   5,  100, 3500],
       [   6,  140, 8000]])

In [77]:
quantity = d[::,0:1:]
quantity

array([[1],
       [4],
       [5],
       [6]])

In [82]:
price = quantity * d[::,1:2:]
cp

array([[100],
       [480],
       [500],
       [840]])

In [83]:
sale = d[::,2::]  
sp

array([[ 200],
       [3000],
       [3500],
       [8000]])

In [85]:
profit = sale - price 
profit

array([[ 100],
       [2520],
       [3000],
       [7160]])

In [89]:
profit.sum()

np.int64(12780)

In [90]:
d

array([[   1,  100,  200],
       [   4,  120, 3000],
       [   5,  100, 3500],
       [   6,  140, 8000]])

In [93]:
sp=d[::,2]
sp

array([ 200, 3000, 3500, 8000])

### Practise Questions

In [96]:
array = np.array([1,2,3,4,5,6,7,8,9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
array[2:7]

array([3, 4, 5, 6, 7])

In [99]:
arr = np.array([10,20,30,40,50,60,70,80])
arr

array([10, 20, 30, 40, 50, 60, 70, 80])

In [101]:
arr[:4:]

array([10, 20, 30, 40])

In [105]:
arr[:4:-1]

array([80, 70, 60])

In [107]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [108]:
arr[::2]

array([10, 30, 50, 70, 90])

In [109]:
arr[::-1]

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [112]:
arr[3::]

array([ 40,  50,  60,  70,  80,  90, 100])

In [114]:
arr[:5]

array([10, 20, 30, 40, 50])

In [116]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [117]:
arr[1::3]

array([ 1,  4,  7, 10, 13, 16, 19])

In [118]:
arr[1:len(arr)-1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [119]:
arr = np.array([5,10,15,20,15,30])
arr

array([ 5, 10, 15, 20, 15, 30])

In [124]:
arr[1:4:]=[0,0,0]
arr

array([ 5,  0,  0,  0, 15, 30])

In [126]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
arr[0]

array([0, 1, 2])

In [131]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [134]:
arr[15:4:-1]

array([16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6])

In [135]:
arr[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])