In [2]:
#install requires lib / import
import numpy as np

### Scalar

In [5]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split'

In [6]:
len(dir(np))

535

In [8]:
arr = np.array(10)
arr

array(10)

In [9]:
arr.shape

()

In [10]:
arr.size

1

In [12]:
arr.ndim  # dimension

0

### Vector

In [14]:
arr = np.array([10 , 20 , 30 , 40 , "rohan"])
arr

array(['10', '20', '30', '40', 'rohan'], dtype='<U21')

In [15]:
arr = np.array([10 , 20 , 30 , 40])
arr

array([10, 20, 30, 40])

In [16]:
arr.shape

(4,)

In [17]:
arr.size  # No. of element present in the array
#length and size are not equal

4

In [18]:
len(arr)

4

In [20]:
arr.ndim

1

In [21]:
ls = [10 , 20 , 30 , 40 , 50]
ls

[10, 20, 30, 40, 50]

In [22]:
ls + 20

TypeError: can only concatenate list (not "int") to list

In [23]:
arr

array([10, 20, 30, 40])

In [25]:
arr + 20  # element wise operation performed

array([30, 40, 50, 60])

In [26]:
ls

[10, 20, 30, 40, 50]

In [27]:
for i in ls:
    print(i + 20)

30
40
50
60
70


In [28]:
arr

array([10, 20, 30, 40])

In [29]:
ls

[10, 20, 30, 40, 50]

In [30]:
ls[3]

40

In [31]:
arr

array([10, 20, 30, 40])

In [32]:
arr[3]

np.int64(40)

In [38]:
arr[[0,3]]       # multiple fetching allowed in array but not allowed in list

array([10, 40])

In [36]:
ls[[0,1]]

TypeError: list indices must be integers or slices, not list

In [39]:
arr

array([10, 20, 30, 40])

In [41]:
arr > 20     # ---> Boolean indexes

array([False, False,  True,  True])

In [42]:
arr[arr>20]   

array([30, 40])

In [45]:
arr[[True , False , True , True]]  # the value which are true is fetched and those who are false are not fetched

array([10, 30, 40])

In [46]:
arr = np.random.randint(1,40,30)  #---> 1 to 40 random values and only 30

In [47]:
arr

array([13,  2, 15, 39, 31,  1, 22, 12, 10,  9,  4,  4, 14, 24,  7, 25, 26,
       36, 13, 10,  5, 27, 14, 14, 27, 26, 28, 37, 27, 29], dtype=int32)

In [48]:
arr > 22

array([False, False, False,  True,  True, False, False, False, False,
       False, False, False, False,  True, False,  True,  True,  True,
       False, False, False,  True, False, False,  True,  True,  True,
        True,  True,  True])

In [50]:
arr[arr>22]

array([39, 31, 24, 25, 26, 36, 27, 27, 26, 28, 37, 27, 29], dtype=int32)

Logical operatin --> Bitwise(for fast calculation)

In [53]:
arr[(arr > 20) | (arr < 40)]

array([13,  2, 15, 39, 31,  1, 22, 12, 10,  9,  4,  4, 14, 24,  7, 25, 26,
       36, 13, 10,  5, 27, 14, 14, 27, 26, 28, 37, 27, 29], dtype=int32)

In [54]:
(arr>20) & (arr < 40)

array([False, False, False,  True,  True, False,  True, False, False,
       False, False, False, False,  True, False,  True,  True,  True,
       False, False, False,  True, False, False,  True,  True,  True,
        True,  True,  True])

In [55]:
arr[(arr>20) & (arr < 40)]

array([39, 31, 22, 24, 25, 26, 36, 27, 27, 26, 28, 37, 27, 29],
      dtype=int32)

In [57]:
arr[~((arr > 20) & (arr < 40))]

array([13,  2, 15,  1, 12, 10,  9,  4,  4, 14,  7, 13, 10,  5, 14, 14],
      dtype=int32)

### Slicing

In [65]:
arr

array([13,  2, 15, 39, 31,  1, 22, 12, 10,  9,  4,  4, 14, 24,  7, 25, 26,
       36, 13, 10,  5, 27, 14, 14, 27, 26, 28, 37, 27, 29], dtype=int32)

In [59]:
arr[0:4]   # last one(4) is not included

array([13,  2, 15, 39], dtype=int32)

In [60]:
arr[-1:-4]   

array([], dtype=int32)

In [61]:
1 + (-1)

0

In [73]:
arr[-1:-4:-1]     #start form backward in oppostie direction

array([29, 27, 37], dtype=int32)

In [63]:
-1 + (-1)

-2

In [64]:
-2 + (-1)

-3

In [66]:
arr

array([13,  2, 15, 39, 31,  1, 22, 12, 10,  9,  4,  4, 14, 24,  7, 25, 26,
       36, 13, 10,  5, 27, 14, 14, 27, 26, 28, 37, 27, 29], dtype=int32)

In [67]:
arr[::]

array([13,  2, 15, 39, 31,  1, 22, 12, 10,  9,  4,  4, 14, 24,  7, 25, 26,
       36, 13, 10,  5, 27, 14, 14, 27, 26, 28, 37, 27, 29], dtype=int32)

In [68]:
arr[0:4]

array([13,  2, 15, 39], dtype=int32)

In [70]:
arr[0:10:2]  #jump 2  -> 0+2 =arr[2] ,2+2=arr[4], 4+2=arr[6]

array([13, 15, 31, 22, 10], dtype=int32)

In [71]:
arr[-4:-10]

array([], dtype=int32)

In [72]:
arr[-4:-10:-1]     # (-1) indicates opposite direction m chalna h 
# -1+(-4)=-5, -5+(-1)=-6, -6+(-1)=-7 

array([28, 26, 27, 14, 14, 27], dtype=int32)

In [74]:
arr[2:-8]

array([15, 39, 31,  1, 22, 12, 10,  9,  4,  4, 14, 24,  7, 25, 26, 36, 13,
       10,  5, 27], dtype=int32)