In [1]:
import pandas as pd

### Series

##### Declaration of series 

In [3]:
pd.Series([10, 20, 30, 40])

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
pd.Series([10,20,30,40] , index=["A","B","C","D"])

A    10
B    20
C    30
D    40
dtype: int64

In [6]:
pd.Series({
    "A" : 10 , "B" : 100 , "C" : 200
})

A     10
B    100
C    200
dtype: int64

In [7]:
import numpy as np

In [8]:
arr = np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [9]:
pd.Series(arr)

0    10
1    20
2    30
3    40
dtype: int64

In [13]:
pd.Series(range(10,20 , 2))   # 10 to 20 and step = 2

0    10
1    12
2    14
3    16
4    18
dtype: int64

## Index
- Default Index  --> iloc
- Label Index  --> loc

#### Default Index

In [14]:
s = pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

#### Label Index

In [15]:
s1 = pd.Series([10,20,30,40] , index=["A","B","C","D"])
s1

A    10
B    20
C    30
D    40
dtype: int64

In [16]:
s

0    10
1    20
2    30
3    40
dtype: int64

In [17]:
s[0]

np.int64(10)

In [18]:
s[1]

np.int64(20)

In [21]:
# s[-1]  --> error

### iloc

In [22]:
s.iloc[0]

np.int64(10)

In [23]:
s.iloc[-1]

np.int64(40)

In [24]:
s

0    10
1    20
2    30
3    40
dtype: int64

In [25]:
s.iloc[0:2]

0    10
1    20
dtype: int64

In [26]:
s1

A    10
B    20
C    30
D    40
dtype: int64

In [27]:
s1.iloc[0]

np.int64(10)

In [29]:
# s1.loc[0]   --> error 

In [31]:
s1.loc["A"] , s1.loc["B"]

(np.int64(10), np.int64(20))

In [32]:
s1

A    10
B    20
C    30
D    40
dtype: int64

In [33]:
s1.loc["A":"C"]

A    10
B    20
C    30
dtype: int64

In [34]:
s1.loc[["A","D"]]

A    10
D    40
dtype: int64

In [35]:
s1 = pd.Series([10,20,30,40,50,60,70,80,90,100,110,120,130] , index=["A","B","C","D","E","F","G","H","I","J","K","L","M"])
s1

A     10
B     20
C     30
D     40
E     50
F     60
G     70
H     80
I     90
J    100
K    110
L    120
M    130
dtype: int64

In [37]:
s1.loc["B":"I"]

B    20
C    30
D    40
E    50
F    60
G    70
H    80
I    90
dtype: int64

In [41]:
s1.loc[["A","M","I","J"]]

A     10
M    130
I     90
J    100
dtype: int64

In [42]:
s1.iloc[0:5]

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [44]:
s1.loc["C":"G"]

C    30
D    40
E    50
F    60
G    70
dtype: int64

In [45]:
s1.iloc[-3]

np.int64(110)

### Numpy assesment

In [47]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [48]:
mat[:,0:1]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [49]:
mat[:,0]

array([ 1,  6, 11, 16, 21])

In [50]:
np.diag(mat)

array([ 1,  7, 13, 19, 25])

In [52]:
mat[::-1,::-1]

array([[25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [53]:
mat[mat>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [57]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [55]:
mat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [56]:
mat.sum()

np.int64(325)

In [59]:
mat.std()

np.float64(7.211102550927978)

In [60]:
mat.mean()

np.float64(13.0)

In [61]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [70]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
np.random.randn(25)

array([-0.19886302,  0.01029232, -2.41329798,  0.50436621,  1.00756538,
       -0.00903701,  0.38719861, -0.78220567, -0.05246828, -1.5826279 ,
       -0.78290263, -0.47963506, -0.15344557, -0.36532304, -0.40940994,
        0.71626115,  0.36787714, -1.99289216,  0.65786168, -0.60998138,
       -0.64974223,  0.38572603,  0.4900511 ,  0.58075121,  1.1083161 ])

In [88]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
np.random.randint(0,10,5)

array([3, 0, 7, 2, 1], dtype=int32)

In [90]:
np.random.random((3,3))

array([[0.85452241, 0.58353017, 0.16314942],
       [0.02288554, 0.48308549, 0.73110769],
       [0.90666526, 0.84909828, 0.63685006]])

In [95]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [96]:
arr.size

20

In [97]:
arr.ndim

2

In [105]:
np.full((2,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])