In [1]:
#importing required libraries
import numpy as np
import pandas as pd

# What is Pandas ?


- Pandas is an open-source Python library for data manipulation, cleaning, analysis, and visualization.

- It is built on Numpy, which means it provides fasst vectorized operations.

- Pandas is optimized for tabular data (like Excel sheets, SQL tables, CSV files).

# Key Terms
- Multivariate  (Univariate -- Normal distribution , Bivariate -- if Age increase, weight is also increased)
- Data wrangling  (a part of Data Manipulation)

# Key featurs:
- Fast and efficient DataFrame object for data manipulation.
- Handling of missing data.
- Flexible reshaping and pivoting of datasets.
- Label-based slicing, indexing, and subsetting.
- Merging and joining of datasets.
- Time series functionality
- Integration with visualization libraries like Matpolib.
       

In [7]:
import pandas as pd

---> pip install pandas (if not installed)

# Pandas consist of three main data structures
- series ---> 1D
- DataFrame ---> 2D
- Panel ---> 3D

## Series

           1D Array

In [9]:
s = pd.Series([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [10]:
type(s)

pandas.core.series.Series

In [11]:
np.array([10,20,30,40,50])

array([10, 20, 30, 40, 50])

        using dictionary

In [13]:
pd.Series({
    "A" : 10 , "B" : 20 , "C" : 40 , "D" : 100
})

A     10
B     20
C     40
D    100
dtype: int64

In [14]:
pd.Series([10,100,200,400] , index = ["A","B","C","D"])

A     10
B    100
C    200
D    400
dtype: int64

In [28]:
arr = np.array([10,200,400,800])
arr

array([ 10, 200, 400, 800])

         Series using array 

In [29]:
s1 = pd.Series(arr)
s1

0     10
1    200
2    400
3    800
dtype: int64

In [30]:
arr

array([ 10, 200, 400, 800])

In [31]:
arr[0]=1000

In [32]:
s1

0    1000
1     200
2     400
3     800
dtype: int64

    copy true --> Independent copy

In [34]:
s1=pd.Series(arr,copy=True)
s1

0    1000
1     200
2     400
3     800
dtype: int64

In [37]:
arr[0]=800

In [38]:
arr[0]

np.int64(800)

In [39]:
s1

0    1000
1     200
2     400
3     800
dtype: int64

In [36]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [21]:
s-10

0     0
1    10
2    20
3    30
4    40
dtype: int64

In [22]:
s+10

0    20
1    30
2    40
3    50
4    60
dtype: int64

In [23]:
s>10

0    False
1     True
2     True
3     True
4     True
dtype: bool

In [24]:
s[s>10]

1    20
2    30
3    40
4    50
dtype: int64

In [40]:
s*2

0     20
1     40
2     60
3     80
4    100
dtype: int64

In [41]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [42]:
s1

0    1000
1     200
2     400
3     800
dtype: int64

In [43]:
s+s1

0    1010.0
1     220.0
2     430.0
3     840.0
4       NaN
dtype: float64

In [44]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [45]:
s[0]

np.int64(10)

In [46]:
s[-1]

KeyError: -1

# **`Two type of index`**
    - Default Index --> Automatically
    - Label Index --> User Defined


    iloc
    loc

In [48]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [49]:
s.iloc[1:3]

1    20
2    30
dtype: int64

In [50]:
s.loc[1:3]

1    20
2    30
3    40
dtype: int64